openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:9090
    description: Generated server url
paths:
  /chart/hla/coverage-plot:
    get:
      tags:
        - hla-chart-controller
      operationId: generateCoveragePlotChart
      parameters:
        - name: runId
          in: query
          required: true
          schema:
            type: string
        - name: sampleId
          in: query
          required: true
          schema:
            type: string
        - name: gene
          in: query
          required: true
          schema:
            type: string
        - name: chartTypes
          in: query
          required: true
          schema:
            type: array
            items:
              type: string
              enum:
                - BASE64
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResponseDto'
  /chart/hla/base-variation-plot:
    get:
      tags:
        - hla-chart-controller
      operationId: generateBaseVariationPlotChart
      parameters:
        - name: runId
          in: query
          required: true
          schema:
            type: string
        - name: sampleId
          in: query
          required: true
          schema:
            type: string
        - name: gene
          in: query
          required: true
          schema:
            type: string
        - name: chartTypes
          in: query
          required: true
          schema:
            type: array
            items:
              type: string
              enum:
                - BASE64
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ResponseDto'
components:
  schemas:
    ChartResult:
      type: object
      properties:
        base64:
          type: string
    ResponseDto:
      type: object
      properties:
        appCode:
          type: integer
          format: int32
        message:
          type: string
        data:
          $ref: '#/components/schemas/ChartResult'