spring:
    profiles:
        group:
            local:
                - default
    devtools:
        livereload:
            enabled: true
server:
    port: 9090
chart-service:
    selenium-service-url: http://192.168.1.30:4444/wd/hub
    result-service-url: http://localhost:9090