spring:
    config:
        activate:
            on-profile: dev
    devtools:
        livereload:
            enabled: true
server:
    port: 9090
chart-service:
    result-service-url: http://localhost:28080