spring:
    profiles:
        group:
          local:
              - default
    devtools:
        livereload:
            enabled: true
logging:
    level:
        root: info
chart-service:
    selenium-service-url: http://localhost:4444/wd/hub
    result-service-url: http://localhost:9090