spring:
    config:
        activate:
            on-profile: prod
    jackson:
        default-property-inclusion: non_null
    thymeleaf:
        prefix: classpath:templates/
        suffix: .html
        cache: false
        enabled: true
server:
    servlet:
        context-path: /
        session:
            timeout: 600s
    tomcat:
        uri-encoding: UTF-8
        threads:
            min-spare: 20
            max: 200
springdoc:
    default-produces-media-type: application/json;charset=UTF-8
    default-consumes-media-type: application/json;charset=UTF-8
    cache:
        disabled: true
    api-docs:
        path: /api/v3/docs
    swagger-ui:
        path: /api/v3/swagger-ui.html