spring:
    profiles:
        group:
          local:
              - default
    devtools:
        livereload:
            enabled: true
logging:
    level:
        root: info
chart-service:
    result-service-url: http://localhost:28080