version: '3.1'

services:
  postgres_chart_service:
    container_name: postgres_chart_service
    image: postgres:14.6
    restart: always
    environment:
      POSTGRES_DB: chart_service
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root1234
    ports:
      - "15432:5432"